[package]
name = "simple_client"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[dependencies]
tokio = { version = "1.24.2", features = ["sync"] }
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10"